# pyproject.toml

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "socket_wrapper" 
version = "0.3.0"
description = "Python wrapper for the Woolfson group’s SOCKET KIH detection tool"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Mikel Martinez Goikoetxea", email = "mikel.martinez@tuebingen.mpg.de " }
]

[tool.setuptools.package-data]
"socket_wrapper" = ["./data/SOCKET/socket2_linux",
                    "./data/sample_PDBs/*.pdb"]

[project.scripts]
socket_check_install = "socket_wrapper.scripts.check_install:main"
